server:
  port: 8080
feign: 
  okhttp: 
    enabled: false
  httpclient: 
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      openApiFeignClient: 
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

#设置hystrix超时时间，默认hystrix超时1秒即会进入failback
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 5000
spring:
  sleuth:
    feign:
      enabled: true
      processor:
        enabled: true
    messaging:
      rabbit:
        enabled: true
  application:
    admin:
      enabled: true
    name: feignClient
open:
  platform:
    url: http://172.20.9.104
    appkey: 10181
    appsecret: 024698EAE56924B2558D0575297829B8
logging:
  config: classpath:log-dev.xml
  level:
    com:
      kye:
        serviceaggregator:
          openapi:
            OpenApiFeignClient : debug
            OpenApi : debug